### ISSUE TITLE
Xbox axis #5 not working

### ISSUE THREAD

**Issue by Samasaur1** [Roobotics-FRC/RooBot2018#6]
The 5th axis of the xBox controller doesn't work - for reference, that's the intake controller. We can try to fix this, possibly by getting a new controller, or we can assign it to a different axis. What do you guys think?

**Comment by jrr6** [comment]
A new controller would be optimal, but in the meantime, why not use the POV pad?

**Comment by jrr6** [comment]
Xbox axis 5 appears to be working again as of today. We were able to see hardware responses as a result of input using the axis, and its outputs also successfully registered on the Driver Station. I'm closing this issue unless and until we have reason to suspect that there is a problem with the joystick; I'm inclined to think that the issues on 2/24 were either laptop- or USB-related or a one-time fluke.

**Comment by thefangbear** [comment]
Reopening this issue as both controllers (including "spare") has this issue (?)

**Comment by Samasaur1** [comment]
Today we switched the intake to be controllable from the D-pad. Even though the issue still remains, I'm closing this as it doesn't affect us anymore.


Notes if required in the future:
The input shows up in the Driver Station, but the program doesn't get any input. This has been tested with multiple controllers. While it worked once, it has never done so again.
