### ISSUE TITLE
git workflow during and after first competition

### ISSUE THREAD

**Issue by thefangbear** [Roobotics-FRC/RooBot2018#7]
Suggestions:
    - Do not merge. Instead, rename `elevators` to `hatboro-horsham`.
    - Work only on that branch during competition (we can fork from there if needed)
    - Afterwards, we do manual cherrypicks from there and rewrite the code. Either start using `development` or start from another branch.
    - At next competition, repeat this procedure.

This should keep efficiency at a maximum without severely adding to our technical debts or affecting the quality of other branches.

**Comment by thefangbear** [comment]
@aaplmath @Samasaur1 

Comments please.

**Comment by jrr6** [comment]
@thefangbear This would be an ideal approach—unfortunately, it seems that we need fully-working code for testing by today. I made sure to preserve all branch histories—it will be trivial, if need be, to revert all of my merges—but at this point, it seems like just getting a fully-functional code base is our top priority.

**Comment by Samasaur1** [comment]
Furthermore, testing today shows no problems with the merged development, so I think we're OK

**Comment by thefangbear** [comment]
OK, LGTM.
